### ISSUE TITLE
With latest code, observing the -verbose option is removed. Can we add it back?

### ISSUE THREAD

**Issue by ketanarlulkar** [Seagate/s3bench#16] opened 2021-05-18 03:50 UTC
Seeing `flag provided but not defined: -verbose`

**Comment by sachitanands** [comment] 2021-08-23 05:02
Hi @ketanarlulkar  could you please provide more details about this ..
e.g. which script you are seeing this issue 
cc @nileshgovande

**Comment by cortx-admin** [comment] 2021-08-23 05:09
> Sachitanand Shelake commented in Jira Server:

Awaiting inputs on this Github issue ..

**Comment by cortx-admin** [comment] 2021-08-23 06:17
> Nilesh Govande commented in Jira Server:

Please add more details [~528894]

**Comment by ketanarlulkar** [comment] 2021-08-23 06:58
Earlier -verbose option used to show operation status for each object, now If I pass -verbose option to s3bench it shows error

    [root@ssc-vm-rhev4-0569 ~]# go run s3bench -accessKey KEY -accessSecret KEY -numClients=2 -numSamples=10 -objectNamePrefix=loadgen -objectSize=4Kb -bucket=loadgen -endpoint=https://s3.seagate.com -verbose
    flag provided but not defined: -verbose
    Usage of /tmp/go-build275148474/b001/exe/s3bench:
    -TLSHandshakeTimeout int
          Specifies the maximum amount of time waiting to wait for a TLS handshake. Zero means no timeout
    -accessKey string
          the S3 access key
    -accessSecret string
          the S3 access secret
    -bucket string
          the bucket for which to run the test (default "bucketname")

**Comment by cortx-admin** [comment] 2021-08-23 07:06
> Ketan Anil Arlulkar commented in Jira Server:

Earlier -verbose option used to show operation status for each object, now If I pass -verbose option to s3bench it shows error


{noformat}
[root@ssc-vm-rhev4-0569 ~]# go run s3bench -accessKey KEY -accessSecret KEY -numClients=2 -numSamples=10 -objectNamePrefix=loadgen -objectSize=4Kb -bucket=loadgen -endpoint=https://s3.seagate.com -verbose
flag provided but not defined: -verbose
Usage of /tmp/go-build275148474/b001/exe/s3bench:
-TLSHandshakeTimeout int
      Specifies the maximum amount of time waiting to wait for a TLS handshake. Zero means no timeout
-accessKey string
      the S3 access key
-accessSecret string
      the S3 access secret
-bucket string
      the bucket for which to run the test (default "bucketname")
{noformat}

**Comment by cortx-admin** [comment] 2021-08-24 09:16
> Nilesh Govande commented in Jira Server:

[~528894] I assume this is s3bench utility issue?

**Comment by cortx-admin** [comment] 2021-08-24 09:16
> Nilesh Govande commented in Jira Server:

COnverting to story and moving this to backlog.

**Comment by cortx-admin** [comment] 2021-10-12 04:40
> Nilesh Govande commented in Jira Server:

This is a cliant side tools enhancement and [~933222] can we seek help from CFT/Perf teams to get this option added ? [ Triage for EOS-25327 would have been easier]

[~525865] can guide/overlook/mentor

CC [~755344]

**Comment by t7ko-seagate** [comment] 2021-10-12 12:57
`-verbose` option is not longer needed for latest s3bench.  By default, s3bench creates a very detailed log file, in the folder where you run it.  That file has name in form `s3bench-YYYY-MM-DD-HH-MM-SS-nnnnn.log`, and includes all the same output which was previously printed on console, and more.  So I will be closing this bug with "By Design".

**Closed as completed by t7ko-seagate** 2021-10-12 12:57 UTC
Labels: [it]added

**Comment by cortx-admin** [comment] 2021-10-12 13:04
> Ivan Tishchenko commented in Jira Server:

{{-verbose}} option is not longer needed for latest s3bench.  By default, s3bench creates a very detailed log file, in the folder where you run it.  That file has name in form {{s3bench-YYYY-MM-DD-HH-MM-SS-nnnnn.log}}, and includes all the same output which was previously printed on console, and more.  So I will be closing this bug with "By Design".

**Comment by cortx-admin** [comment] 2021-10-12 13:04
> Ivan Tishchenko commented in Jira Server:

No fix needed.

**Comment by cortx-admin** [comment] 2021-10-12 13:04
> Ivan Tishchenko commented in Jira Server:

No fix needed.

**Comment by cortx-admin** [comment] 2021-10-12 13:04
> Ivan Tishchenko commented in Jira Server:

No QA needed.
